const poemData = [
    { text: "宋", py: "sòng", zh: "春秋时的诸侯国，宋国。", en: "State of Song." },
    { text: "之", py: "zhī", zh: "结构助词，的。", en: "(possessive) of." },
    { text: "丁氏", py: "dīng shì", zh: "姓丁的人家。", en: "The Ding family." },
    { text: "，", punc: true },
    { text: "家", py: "jiā", zh: "家里。", en: "Household." },
    { text: "无井", py: "wú jǐng", zh: "没有水井。", en: "had no well." },
    { text: "而", py: "ér", zh: "表顺承，于是，就。", en: "so" },
    { text: "出", py: "chū", zh: "外出。", en: "went out." },
    { text: "溉汲", py: "gài jí", zh: "浇灌田地、从远处打水。", en: "irrigate and fetch water." },
    { text: "，", punc: true },
    { text: "常", py: "cháng", zh: "经常。", en: "often." },
    { text: "一人", py: "yī rén", zh: "一个人。", en: "one person." },
    { text: "居外", py: "jū wài", zh: "常年停留在外面。", en: "stayed outside." },
    { text: "。", punc: true },
    { text: "及", py: "jí", zh: "介词，等到。", en: "when" },
    { text: "其家", py: "qí jiā", zh: "他们家。", en: "their family" },
    { text: "穿井", py: "chuān jǐng", zh: "开凿水井。", en: "dug a well." },
    { text: "，", punc: true },
    { text: "告人", py: "gào rén", zh: "告诉别人。", en: "told people." },
    { text: "曰", py: "yuē", zh: "说。", en: "said." },
    { text: "：“", punc: true },
    { text: "吾", py: "wú", zh: "我。", en: "I.", exam: true },
    { text: "穿井", py: "chuān jǐng", zh: "挖井。", en: "digging the well.", exam: true },
    { text: "得一人", py: "dé yī rén", zh: "省下或多得到一个劳动力。", en: "gained one person's labor.", exam: true },
    { text: "。”", punc: true },
    { text: "有", py: "yǒu", zh: "有人。", en: "someone" },
    { text: "闻", py: "wén", zh: "听说。", en: "heard" },
    { text: "而", py: "ér", zh: "表顺承。", en: "and" },
    { text: "传之者", py: "chuán zhī zhě", zh: "传播这件事的人。", en: "spread it." },
    { text: "曰", py: "yuē", zh: "说。", en: "said." },
    { text: "：“", punc: true },
    { text: "丁氏", py: "dīng shì", zh: "丁家。", en: "The Ding family" },
    { text: "穿井", py: "chuān jǐng", zh: "挖井。", en: "dug a well" },
    { text: "得一人", py: "dé yī rén", zh: "挖出一个人（误传）。", en: "and dug up a person.", exam: true },
    { text: "。”", punc: true },
    { text: "国人", py: "guó rén", zh: "国都里的人，全国百姓。", en: "People of the state." },
    { text: "道之", py: "dào zhī", zh: "谈论这件事。", en: "talked about it." },
    { text: "，", punc: true },
    { text: "闻之于宋君", py: "wén zhī yú sòng jūn", zh: "这件事被宋国国君听到了。", en: "it was heard by the ruler of Song." },
    { text: "。", punc: true },
    { text: "宋君", py: "sòng jūn", zh: "宋国国君。", en: "The ruler of Song" },
    { text: "令人", py: "lìng rén", zh: "派人。", en: "sent someone" },
    { text: "问之", py: "wèn zhī", zh: "询问这件事。", en: "to ask about it" },
    { text: "于", py: "yú", zh: "向。", en: "from" },
    { text: "丁氏", py: "dīng shì", zh: "丁家。", en: "Ding." },
    { text: "。", punc: true },
    { text: "丁氏", py: "dīng shì", zh: "丁家。", en: "Ding" },
    { text: "对曰", py: "duì yuē", zh: "回答说。", en: "replied." },
    { text: "：“", punc: true },
    { text: "得", py: "dé", zh: "得到。", en: "gained" },
    { text: "一人之使", py: "yī rén zhī shǐ", zh: "一个人的劳动力。", en: "the labor of one person.", exam: true },
    { text: "，", punc: true },
    { text: "非", py: "fēi", zh: "不是。", en: "not" },
    { text: "得一人", py: "dé yī rén", zh: "得到一个人。", en: "getting a person" },
    { text: "于井中", py: "yú jǐng zhōng", zh: "在水井里面。", en: "from the well." },
    { text: "也", py: "yě", zh: "表判断语气。", en: "(particle)" },
    { text: "。”", punc: true },
    { text: "求闻之", py: "qiú wén zhī", zh: "探求听到的传闻消息。", en: "Seeking news", exam: true },
    { text: "若此", py: "ruò cǐ", zh: "像这样（盲目轻信）。", en: "like this." },
    { text: "，", punc: true },
    { text: "不若", py: "bú ruò", zh: "不如。", en: "better not to" },
    { text: "无闻", py: "wú wén", zh: "没有听到。", en: "have heard it." },
    { text: "也", py: "yě", zh: "表感叹。", en: "(particle)" },
    { text: "。", punc: true }
];
